"""Shared data contracts and model definitions for AcadAssist."""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ============================================================================
# Assessment & Quiz Contracts (Person 3)
# ============================================================================

@dataclass
class QuizQuestion:
    """Represents a single quiz question."""

    id: str
    text: str
    options: List[str] = field(default_factory=list)
    correct_answer: str = ""
    explanation: str = ""
    topic: str = ""
    difficulty: str = "medium"


@dataclass
class Quiz:
    """Represents an academic quiz containing multiple questions."""

    id: str
    title: str
    subject: str = ""
    topic: str = ""
    difficulty: str = "medium"
    questions: List[QuizQuestion] = field(default_factory=list)
    created_at: str = ""


@dataclass
class QuizAttempt:
    """Represents a student's attempt on a specific quiz."""

    id: str
    quiz_id: str
    user_id: str = "default_student"
    submitted_answers: Dict[str, str] = field(default_factory=dict)
    timestamp: str = ""


@dataclass
class Mistake:
    """Represents an incorrectly answered question in a quiz attempt."""

    question_id: str
    question_text: str
    student_answer: str
    correct_answer: str
    explanation: str = ""
    topic: str = ""


@dataclass
class QuizResult:
    """Represents the deterministic evaluation result of a quiz attempt."""

    quiz_id: str
    attempt_id: str = ""
    total_questions: int = 0
    correct_count: int = 0
    incorrect_count: int = 0
    score: float = 0.0
    percentage: float = 0.0
    mistakes: List[Mistake] = field(default_factory=list)


@dataclass
class Progress:
    """Represents progress and accuracy metrics for a topic or overall."""

    topic: str = "Overall"
    quizzes_attempted: int = 0
    questions_attempted: int = 0
    correct_count: int = 0
    incorrect_count: int = 0
    accuracy_percentage: float = 0.0


# ============================================================================
# Study Planning Contracts (Person 3)
# ============================================================================

@dataclass
class StudyTask:
    """Represents an individual task within a study plan."""

    id: str
    title: str
    topic: str = ""
    planned_date: str = ""
    is_completed: bool = False


@dataclass
class StudyPlan:
    """Represents a study plan composed of multiple tasks."""

    id: str
    title: str
    subject: str = ""
    tasks: List[StudyTask] = field(default_factory=list)
    created_at: str = ""


# ============================================================================
# Shared Team Contracts (Foundation Stubs for Cross-Module Integration)
# ============================================================================

@dataclass
class Document:
    """Represents an ingested study document."""

    id: str
    title: str
    content: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DocumentChunk:
    """Represents a chunk of a document for indexing and retrieval."""

    id: str
    document_id: str
    text: str
    chunk_index: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RetrievedChunk:
    """Represents a chunk retrieved by the RAG search pipeline."""

    chunk: Optional[DocumentChunk] = None
    score: float = 0.0
    source: str = ""


@dataclass
class SourceReference:
    """Represents a citation or reference source for an AI response."""

    document_id: str
    title: str
    snippet: str = ""
    page: Optional[int] = None


@dataclass
class StudyResponse:
    """Represents a structured study answer or explanation."""

    answer: str
    sources: List[SourceReference] = field(default_factory=list)
    confidence: float = 1.0


@dataclass
class AgentResponse:
    """Represents a response generated by the AI agent coordinator."""

    response_text: str
    intent: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
