import { useEffect, useState } from 'react';
import { CheckCircle2, FileQuestion, History, RotateCcw, Sparkles, Target, X, Clock3, AlertCircle } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useApp, type Quiz } from '../context/AppContext';
import Modal from '../components/ui/Modal';

const TOPICS=['Deadlocks','CPU Scheduling','Memory Management','Transport Layer','Application Layer','Normalization','SVM','Regression','Trees','Graphs'];
const BANK:Record<string,{q:string;options:string[];answer:number;explanation:string}[]>={
 'Deadlocks':[
  {q:'Which condition is required for deadlock?',options:['Preemption of every resource','Circular wait','Unlimited resources','Only one process'],answer:1,explanation:'Circular wait is one of the four necessary Coffman conditions.'},
  {q:'Which technique can prevent circular wait?',options:['Impose a global resource ordering','Increase context switches','Disable interrupts','Use FCFS'],answer:0,explanation:'Ordering resource acquisition prevents cycles in the wait-for graph.'},
  {q:'A process holds one resource while waiting for another. Which condition is this?',options:['Mutual exclusion','Hold and wait','No preemption','Circular wait'],answer:1,explanation:'Hold and wait means a process holds resources while requesting additional resources.'},
 ],
 'CPU Scheduling':[
  {q:'Which scheduling algorithm uses a time quantum?',options:['FCFS','SJF','Round Robin','Priority only'],answer:2,explanation:'Round Robin assigns each ready process a fixed time slice.'},
  {q:'Which algorithm can minimize average waiting time when burst lengths are known?',options:['SJF','FCFS','Round Robin','FIFO paging'],answer:0,explanation:'Shortest Job First is optimal for average waiting time under its standard assumptions.'},
 ],
 'Transport Layer':[
  {q:'Which protocol provides reliable, ordered byte-stream delivery?',options:['UDP','TCP','IP','ARP'],answer:1,explanation:'TCP provides connection-oriented reliable ordered delivery.'},
  {q:'What is a key property of UDP?',options:['Mandatory retransmission','Connectionless delivery','Guaranteed ordering','Three-way handshake'],answer:1,explanation:'UDP is connectionless and does not guarantee delivery or ordering.'},
  {q:'Flow control primarily prevents what?',options:['A sender from overwhelming a receiver','IP address exhaustion','DNS caching','MAC collisions'],answer:0,explanation:'Receiver-side flow control regulates how much data the sender may have outstanding.'},
 ],
 'Normalization':[
  {q:'What is the main purpose of normalization?',options:['Increase redundancy','Reduce update anomalies and redundancy','Remove all keys','Avoid SQL'],answer:1,explanation:'Normalization structures relations to reduce redundancy and anomalies.'},
  {q:'A relation is in 2NF when it is in 1NF and has no?',options:['Primary key','Partial dependency on a composite key','Foreign key','Rows'],answer:1,explanation:'2NF removes partial functional dependencies on a composite candidate key.'},
 ],
 'SVM':[
  {q:'What does a hard-margin SVM try to maximize?',options:['Training errors','Margin between classes','Number of features','Learning rate'],answer:1,explanation:'SVM seeks a separating hyperplane with maximum margin under hard-margin assumptions.'},
  {q:'Which technique allows SVMs to model nonlinear boundaries?',options:['Kernel trick','Dropout','Bagging only','Normalization only'],answer:0,explanation:'Kernels implicitly map inputs into higher-dimensional feature spaces.'},
 ],
};

export default function Assessment(){
 const {subjects,knowledgeMaterials,notes,quizzes,addQuiz,updateQuiz,pushToast}=useApp(); const [params]=useSearchParams();
 const initialSource=(params.get('source')==='document'?'Document':params.get('source')==='notes'?'Notes':'Topic') as 'Topic'|'Document'|'Notes';
 const [source,setSource]=useState<'Topic'|'Document'|'Notes'>(initialSource); const [subject,setSubject]=useState(subjects[0]?.name||'Operating Systems'); const [topic,setTopic]=useState(params.get('material')||'Deadlocks'); const [difficulty,setDifficulty]=useState<Quiz['difficulty']>('Mixed'); const [count,setCount]=useState(10); const [mode,setMode]=useState(false); const [active,setActive]=useState<Quiz|null>(null); const [answers,setAnswers]=useState<Record<string,number>>({}); const [result,setResult]=useState<number|null>(null); const [history,setHistory]=useState(false); const [timer,setTimer]=useState(0); const [confirm,setConfirm]=useState(false);
 useEffect(()=>{if(!mode||result!==null||timer<=0)return;const id=window.setInterval(()=>setTimer(t=>Math.max(0,t-1)),1000);return()=>window.clearInterval(id)},[mode,result,timer]);
 const sourceItems=source==='Document'?knowledgeMaterials.map(x=>x.name):source==='Notes'?notes.map(x=>x.title):TOPICS;
 const generate=()=>{const selectedTopic=source==='Topic'?topic:(sourceItems[0]||'General Study');const bank=BANK[selectedTopic]||BANK['Transport Layer'];const questions=Array.from({length:count},(_,i)=>{const b=bank[i%bank.length];return {id:crypto.randomUUID(),text:source==='Topic'?b.q:`Based on ${selectedTopic}: ${b.q}`,options:[...b.options],answer:b.answer,explanation:b.explanation};});const q:Quiz={id:crypto.randomUUID(),title:`${selectedTopic} — ${difficulty} Practice`,source:selectedTopic,subject,difficulty,questions};addQuiz(q);setActive(q);setAnswers({});setResult(null);setTimer(mode?count*60:0);pushToast('Quiz generated from your selected source')};
 const submit=()=>{if(!active)return;const correct=active.questions.filter(q=>answers[q.id]===q.answer).length;const score=Math.round(correct/active.questions.length*100);updateQuiz(active.id,{score,completedAt:new Date().toISOString()});setResult(score);setConfirm(false);pushToast(`Quiz submitted — ${score}%`)};
 const retry=()=>{if(!active)return;setAnswers({});setResult(null);setTimer(mode?active.questions.length*60:0)};
 return <div className="page-stack"><div className="page-hero"><div><div className="eyebrow">AI ASSESSMENT STUDIO</div><h1>Practice what matters.</h1><p>Create meaningful quizzes from a topic, your documents or your AI notes.</p></div><button className="btn secondary" onClick={()=>setHistory(true)}><History size={16}/>Quiz history</button></div>
 <div className="assessment-layout"><div className="card generator-card"><div className="section-kicker">CREATE A QUIZ</div><h2>AI Quiz Generator</h2><p className="muted">Local mode uses a deterministic question bank. Azure AI can replace this service without changing the UI.</p><div className="source-tabs">{(['Topic','Document','Notes'] as const).map(s=><button key={s} className={source===s?'active':''} onClick={()=>{const items=s==='Topic'?TOPICS:s==='Document'?knowledgeMaterials.map(x=>x.name):notes.map(x=>x.title);setSource(s);setTopic(items[0]||'')}}><FileQuestion size={15}/>From {s}</button>)}</div><label>Subject<select className="select full" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>{source==='Topic'?'Topic':`Select ${source}`}<select className="select full" value={topic} onChange={e=>setTopic(e.target.value)}>{sourceItems.map(x=><option key={x}>{x}</option>)}</select></label><div className="form-grid"><label>Questions<select className="select full" value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,15,20].map(n=><option key={n}>{n}</option>)}</select></label><label>Difficulty<select className="select full" value={difficulty} onChange={e=>setDifficulty(e.target.value as Quiz['difficulty'])}>{['Easy','Medium','Hard','Mixed','Adaptive'].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="toggle-row"><input type="checkbox" checked={mode} onChange={e=>setMode(e.target.checked)}/><span><b>Exam mode</b><small>Timer and final score only.</small></span></label><button className="btn primary large" onClick={generate}><Sparkles size={17}/>Generate quiz</button></div>
 <div className="card how-card"><div className="ai-icon"><Sparkles size={18}/></div><h3>Assessment workflow</h3>{['Choose a source','Set difficulty and question count','Attempt without seeing answers','Review mistakes and explanations','Generate a similar quiz'].map(x=><div className="feature-row" key={x}><CheckCircle2 size={16}/><span>{x}</span></div>)}<div className="callout">Your completed scores are saved locally and feed the Progress page.</div></div></div>
 {active&&<div className="modal-backdrop"><div className="modal quiz-modal"><div className="quiz-head"><div><div className="eyebrow">{mode?'EXAM MODE':'PRACTICE MODE'}</div><h2>{active.title}</h2></div><div className="quiz-status">{result===null?`${Object.keys(answers).length}/${active.questions.length}`:`${result}%`}{mode&&result===null&&timer>0?<span className="timer"><Clock3 size={13}/>{Math.ceil(timer/60)}m</span>:null}</div></div>{result===null?<div className="question-stack">{active.questions.map((q,i)=><div className="question" key={q.id}><b>{i+1}. {q.text}</b><div className="option-grid">{q.options.map((o,j)=><button key={o} className={answers[q.id]===j?'selected':''} onClick={()=>setAnswers(a=>({...a,[q.id]:j}))}>{String.fromCharCode(65+j)}. {o}</button>)}</div></div>)}<div className="modal-actions"><button className="btn secondary" onClick={()=>setActive(null)}><X size={15}/>Exit</button><button className="btn primary" disabled={Object.keys(answers).length<active.questions.length} onClick={()=>setConfirm(true)}><CheckCircle2 size={15}/>Submit</button></div></div>:<div className="result-panel"><div className="result-score">{result}%</div><h2>{result>=80?'Strong result':result>=60?'Good foundation':'Targeted review needed'}</h2><p className="muted">Review the questions you missed before taking another attempt.</p><div className="result-actions"><button className="btn secondary" onClick={retry}><RotateCcw size={15}/>Retry</button><button className="btn secondary" onClick={()=>pushToast('Mistake review is available in this quiz view')}><Target size={15}/>Review mistakes</button><button className="btn primary" onClick={()=>{setActive(null);generate()}}><Sparkles size={15}/>Generate similar</button></div></div>}</div></div>}
 <Modal open={history} onClose={()=>setHistory(false)} title="Quiz history" wide><div>{quizzes.length?quizzes.map(q=><div className="history-row" key={q.id}><div><b>{q.title}</b><small>{q.subject} · {q.difficulty} · {q.questions.length} questions</small></div><span>{q.score===undefined?'Not attempted':`${q.score}%`}</span><button className="btn subtle" onClick={()=>{setActive(q);setAnswers({});setResult(null);setHistory(false)}}>Retry</button></div>):<div className="empty-inline">No completed or generated quizzes yet.</div>}</div></Modal>
 <Modal open={confirm} onClose={()=>setConfirm(false)} title="Submit quiz" subtitle="You cannot change answers after submission."><div className="flex items-start gap-3"><AlertCircle size={20}/><p className="text-sm">You answered {Object.keys(answers).length} of {active?.questions.length||0} questions. Submit now?</p></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setConfirm(false)}>Keep working</button><button className="btn primary" onClick={submit}>Submit quiz</button></div></Modal>
 </div>
}
