import { useState, type CSSProperties } from 'react';
import { ArrowRight, CalendarDays, Check, FileText, Plus, Sparkles, Target, BookOpen, ChevronLeft, ChevronRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp, type CalendarEvent } from '../context/AppContext';
import Modal from '../components/ui/Modal';

const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function Dashboard(){
 const {user,todayPlan,togglePlanItem,courses,events,subjects,addEvent,pushToast}=useApp();const navigate=useNavigate();const [selectedEvent,setSelectedEvent]=useState<CalendarEvent|null>(null);const [aiOpen,setAiOpen]=useState(false);const [day,setDay]=useState(new Date());
 const enrolled=courses.filter(c=>c.enrolled);const important=subjects.filter(s=>enrolled.some(c=>c.name===s.name)).sort((a,b)=>b.progress-a.progress).slice(0,4);const upcoming=events.filter(e=>e.date>=iso(new Date())).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);const done=todayPlan.filter(x=>x.status==='completed').length;const overall=Math.round(enrolled.reduce((a,c)=>a+c.progress,0)/(enrolled.length||1));const month=day.toLocaleString('en-US',{month:'long',year:'numeric'});const days=new Date(day.getFullYear(),day.getMonth()+1,0).getDate();const first=new Date(day.getFullYear(),day.getMonth(),1).getDay();
 const recommendation=important[0]||subjects[0];
 const focus=()=>{if(!recommendation){navigate('/courses');return}const date=iso(new Date());addEvent({id:crypto.randomUUID(),date,title:`Study ${recommendation.name}`,type:'Study Session',subject:recommendation.name,time:'Today',completed:false,notes:'AI-recommended focus session'});pushToast('Recommended study session added to Planner');setAiOpen(false);navigate('/planner')};
 return <div className="page-stack"><div className="page-hero"><div><div className="eyebrow">YOUR STUDY COMMAND CENTER</div><h1>{new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening'}, <span>{user.name}.</span></h1><p>Today’s learning, upcoming deadlines and your next best study action.</p></div><button className="btn primary" onClick={()=>setAiOpen(true)}><Sparkles size={16}/>What should I study?</button></div>
 <div className="dashboard-grid"><section className="dashboard-main"><div className="dashboard-top-grid"><div className="card progress-wheel-card"><div><div className="section-kicker">OVERALL PROGRESS</div><h3>Academic progress</h3><p className="muted">Across your active subjects</p></div><div className="progress-wheel" style={{'--progress':`${overall}%`} as CSSProperties}><div><strong>{overall}%</strong><span>complete</span></div></div><button className="link-btn" onClick={()=>navigate('/progress')}>View analytics <ArrowRight size={14}/></button></div><div className="card focus-card"><div className="section-title-row"><div><div className="section-kicker">TODAY'S FOCUS</div><h3>Do these next</h3></div><span className="soft-badge">{done}/{todayPlan.length} done</span></div>{todayPlan.slice(0,5).map(x=><div className="focus-item" key={x.id}><button className={`check ${x.status==='completed'?'done':''}`} onClick={()=>togglePlanItem(x.id)}>{x.status==='completed'&&<Check size={13}/>}</button><div><b>{x.title}</b><small>{x.time} · {x.duration}</small></div><button className="mini-btn" onClick={()=>navigate('/planner')}>Open</button></div>)}<button className="full-btn" onClick={()=>navigate('/planner')}>Open full planner <ArrowRight size={14}/></button></div></div>
 <div className="section-title-row"><div><div className="section-kicker">IMPORTANT SUBJECTS</div><h2>Keep these moving</h2></div><button className="link-btn" onClick={()=>navigate('/courses')}>Manage subjects <ArrowRight size={14}/></button></div><div className="subject-grid">{important.map(s=>{const c=enrolled.find(c=>c.name===s.name);return <button className="card subject-card text-left" key={s.id} onClick={()=>navigate('/progress')}><div className="subject-icon" style={{background:`${s.color}18`,color:s.color}}><BookOpen size={17}/></div><div className="subject-head"><b>{s.name}</b><span>{s.progress}%</span></div><div className="progress-track"><span style={{width:`${s.progress}%`,background:s.color}}/></div><small>{s.topicsCompleted}/{s.totalTopics} topics · {c?.estimatedHours||0}h course</small></button>})}</div>
 <div className="section-title-row"><div><div className="section-kicker">UPCOMING</div><h2>Events & deadlines</h2></div><button className="link-btn" onClick={()=>navigate('/planner')}>Calendar <ArrowRight size={14}/></button></div><div className="upcoming-list card">{upcoming.length?upcoming.map(e=><button className="upcoming-row w-full text-left" key={e.id} onClick={()=>setSelectedEvent(e)}><div className="event-date"><strong>{new Date(e.date+'T00:00:00').getDate()}</strong><small>{new Date(e.date+'T00:00:00').toLocaleString('en-US',{month:'short'})}</small></div><div className="flex-1"><b>{e.title}</b><small>{e.subject||'AcadAssist'} {e.time?`· ${e.time}`:''}</small></div><span className="soft-badge">{e.type}</span></button>):<div className="empty-inline">No upcoming events. Add one in Planner.</div>}</div></section>
 <aside className="dashboard-side"><div className="card calendar-card"><div className="calendar-head"><button className="icon-button" onClick={()=>setDay(new Date(day.getFullYear(),day.getMonth()-1,1))}><ChevronLeft size={15}/></button><strong>{month}</strong><button className="icon-button" onClick={()=>setDay(new Date(day.getFullYear(),day.getMonth()+1,1))}><ChevronRight size={15}/></button></div><div className="calendar-week">{['S','M','T','W','T','F','S'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="calendar-days">{Array.from({length:first}).map((_,i)=><span key={'x'+i}/>) }{Array.from({length:days},(_,i)=>i+1).map(n=>{const ds=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;const has=events.some(e=>e.date===ds);const isToday=ds===iso(new Date());return <button key={n} className={`${isToday?'today ':''}${has?'has-event':''}`} onClick={()=>navigate(`/planner?date=${ds}`)}>{n}{has&&<i/>}</button>})}</div><button className="full-btn" onClick={()=>navigate('/planner')}><CalendarDays size={14}/>Open calendar</button></div>
 <div className="card ai-reco"><div className="ai-icon"><Sparkles size={18}/></div><div className="section-kicker">AI STUDY RECOMMENDATION</div><h3>What should you study today?</h3><p>{recommendation?`Focus on ${recommendation.name} and its least-complete topics for the next session.`:'Add a course to generate a recommendation.'}</p><button className="btn primary" onClick={()=>setAiOpen(true)} disabled={!recommendation}>Start recommended session</button></div>
 <div className="card quick-card"><div className="section-title-row"><h3>Quick actions</h3><span>+</span></div><button onClick={()=>navigate('/knowledge')}><FileText size={16}/>Upload material <ArrowRight size={14}/></button><button onClick={()=>navigate('/assessment')}><Target size={16}/>Create AI quiz <ArrowRight size={14}/></button><button onClick={()=>navigate('/planner')}><Plus size={16}/>Add study task <ArrowRight size={14}/></button></div></aside></div>
 <Modal open={!!selectedEvent} onClose={()=>setSelectedEvent(null)} title={selectedEvent?.title||'Event'} subtitle={selectedEvent?.subject||'Academic schedule'}><p className="text-sm">{selectedEvent?.type} · {selectedEvent?.date}{selectedEvent?.time?` · ${selectedEvent.time}`:''}</p>{selectedEvent?.notes&&<p className="muted text-sm mt-2">{selectedEvent.notes}</p>}<div className="modal-actions"><button className="btn secondary" onClick={()=>{setSelectedEvent(null);navigate('/planner')}}>Open planner</button><button className="btn primary" onClick={focus}>Study this next</button></div></Modal>
 <Modal open={aiOpen} onClose={()=>setAiOpen(false)} title="What should I study today?" subtitle="Local recommendation based on active subjects and progress"><p className="text-sm">{recommendation?<>Focus on <b>{recommendation.name}</b>. It currently has {recommendation.progress}% progress, so a focused session can target its remaining topics.</>:<>Add a course from Courses first.</>}</p><div className="modal-actions"><button className="btn secondary" onClick={()=>{setAiOpen(false);navigate('/assessment')}}>Take a quiz</button><button className="btn primary" onClick={focus}>Add study session</button></div></Modal></div>
}
