"""Provisional data models for the RAG module.

These models serve as provisional representations until shared contracts
(e.g., contracts/models.py) are introduced across all modules.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class RetrievedChunk:
    """Represents a chunk of text retrieved from a knowledge source."""

    chunk_id: str
    content: str
    source: str
    page: Optional[int] = None
    score: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SourceReference:
    """Represents an academic source citation attached to a study response."""

    source: str
    page: Optional[int] = None
    chunk_id: Optional[str] = None
    snippet: Optional[str] = None


@dataclass
class StudyResponse:
    """Represents the final answer generated by the RAG pipeline."""

    question: str
    answer: str
    sources: List[SourceReference] = field(default_factory=list)
    context_used: str = ""
    confidence: float = 1.0
